In [38]:
from torch.nn.utils.rnn import PackedSequence, pack_padded_sequence, pad_packed_sequence, pad_sequence, pack_sequence
import torch
import torch.nn as nn
import numpy as np

In [67]:
x_seq = [torch.tensor([[1.,2.], [3.,4.], [5.,6.]]), torch.tensor([[7.,8.], [9.,10.]]),
 torch.tensor([[11., 12.], [13., 14.], [15., 16.], [17., 18.]])]
x_padded = pad_sequence(x_seq, batch_first=True)

In [68]:
x_padded = pad_sequence(x_seq, batch_first=True)
lengths = torch.as_tensor([v.size(0) for v in x_seq])
x_packed = pack_padded_sequence(x_padded, lengths, batch_first=True, enforce_sorted = False)

pad_packed_sequence(x_packed, batch_first=True)

(tensor([[[ 1.,  2.],
          [ 3.,  4.],
          [ 5.,  6.],
          [ 0.,  0.]],
 
         [[ 7.,  8.],
          [ 9., 10.],
          [ 0.,  0.],
          [ 0.,  0.]],
 
         [[11., 12.],
          [13., 14.],
          [15., 16.],
          [17., 18.]]]),
 tensor([3, 2, 4]))

In [69]:
x, y = pad_packed_sequence(x_packed, batch_first=True)
y
x

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 0.,  0.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[11., 12.],
         [13., 14.],
         [15., 16.],
         [17., 18.]]])

SyntaxError: unexpected EOF while parsing (2977427633.py, line 1)

In [97]:
model = nn.LSTM(input_size = 2, hidden_size=1, num_layers=1, bidirectional=True, batch_first=True)



output, _ = model(x_packed)

output, input_sizes = pad_packed_sequence(output, batch_first=True)

output

tensor([[[-3.7654e-03, -5.0252e-01],
         [ 1.0016e-04, -4.4782e-01],
         [ 2.1859e-04, -3.5612e-01],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 5.3202e-05, -2.6492e-01],
         [ 1.0374e-05, -1.7264e-01],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 1.8118e-06, -1.0672e-01],
         [ 2.9769e-07, -6.2241e-02],
         [ 4.7116e-08, -3.5255e-02],
         [ 7.2860e-09, -1.9610e-02]]], grad_fn=<IndexSelectBackward0>)

In [101]:

outputs_0 = output[:, 0, :]
outputs_0


tensor([[-3.7654e-03, -5.0252e-01],
        [ 5.3202e-05, -2.6492e-01],
        [ 1.8118e-06, -1.0672e-01]], grad_fn=<SliceBackward0>)

In [115]:

outputs_end = torch.stack([output[batch_idx, seq_length - 1, :] for batch_idx, seq_length in enumerate(input_sizes)], dim = 0)

outputs_end


tensor([[ 2.1859e-04, -3.5612e-01],
        [ 1.0374e-05, -1.7264e-01],
        [ 7.2860e-09, -1.9610e-02]], grad_fn=<StackBackward0>)

In [117]:
torch.cat((outputs_0, outputs_end), dim = 1)

tensor([[-3.7654e-03, -5.0252e-01,  2.1859e-04, -3.5612e-01],
        [ 5.3202e-05, -2.6492e-01,  1.0374e-05, -1.7264e-01],
        [ 1.8118e-06, -1.0672e-01,  7.2860e-09, -1.9610e-02]],
       grad_fn=<CatBackward0>)

In [16]:
#Generates all the indices that correspond to a batch
batch_indices = [[1,2,3,4,5,6,7,8,9,10,11,12,13,14][i: i + 3] for i in range(0, 14, 3)]

batch_indices

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14]]

In [ ]:
torch.cat((outputs_0, outputs_end), dim = 2)

torch.float64

torch.float32